/*
Copyright (c) 2025 Blue Robotics North Inc.

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/


//*******************************************************************************************
//Includes
//*******************************************************************************************
#include <blueberry-receiver.h>
#include <blueberry-transcoder.h>
#include <blueberry-parser.h>


//*******************************************************************************************
//Defines
//*******************************************************************************************



//*******************************************************************************************
//Types
//*******************************************************************************************

//*******************************************************************************************
//Variables
//*******************************************************************************************



//*******************************************************************************************
//Function Prototypes
//*******************************************************************************************


/**
 * Receive one bytes from the queue.
 * This is intended for use with a UART
 * This function will test the CRC
 * the length field of the Bb packet field is used as a state variable. Zero indicates the state is reset. After that it indicates how many bytes have been successfully received
 * @param buf - the buffer for this packet, also the state of the receive routine
 * @return BB_GOOD if a valid packet was received, BB_FAIL if the packet was bad, BB_INCOMPLETE if it's good so far but more bytes are needed
 */
static BbResult blueberryReceiveByte(Bb* bb);

/**
 * Decodes a packet from the start of a buffer, assuming it is all there
 * This is indended for use with ethernet
 * This function will not test the CRC
 * This function will discard the queue contents if the packet fails the checks
 * This is implemented with function pointers. I tried to avoid them but it allows easy inclusion into the autogenerated code
 * @param buf - the buffer for this packet, also the state of the receive routine
 * @return BB_GOOD if a valid packet was received, BB_FAIL if the packet was bad
 */
static BbResult blueberryReceivePacket(Bb* buf);
//*******************************************************************************************
//Code
//*******************************************************************************************

/**
 * Receive one bytes from the queue.
 * This is intended for use with a UART
 * This function will test the CRC
 * the length field of the Bb packet field is used as a state variable. Zero indicates the state is reset. After that it indicates how many bytes have been successfully received
 * @param buf - the buffer for this packet, also the state of the receive routine
 * @return BB_GOOD if a valid packet was received, BB_FAIL if the packet was bad, BB_INCOMPLETE if it's good so far but more bytes are needed
 */
static BbResult blueberryReceiveByte(Bb* buf){
	BbResult result = BB_INCOMPLETE;

	++(buf->length);

	if(!minBbLengthCheck(buf)){
		if(!checkBbPreamble(buf)){
			result = BB_FAIL;
		}
	} else if(checkBbLength(buf)){
		if(checkBbCrc(buf)){
			result = BB_GOOD;//we have a valid packet
			//any remaining bytes should be checked after this packet has been consumed
		} else {
			result = BB_FAIL;
		}
	}
	return result;
}

/**
 * Decodes a packet from the start of a buffer, assuming it is all there
 * This is indended for use with ethernet
 * This function will not test the CRC
 * This function will discard the queue contents if the packet fails the checks
 * This is implemented with function pointers. I tried to avoid them but it allows easy inclusion into the autogenerated code
 * @param buf - the buffer for this packet, also the state of the receive routine
 * @return BB_GOOD if a valid packet was received, BB_FAIL if the packet was bad
 */
static BbResult blueberryReceivePacket(Bb* buf){
	BbResult result = BB_FAIL;

	if(minBbLengthCheck(buf)){
		if(checkBbPreamble(buf)){
			if(checkBbLength(buf)){
				result = BB_GOOD;
			}
		}
	}
	return result;
}


/**
 * Decodes a packet from the start of a buffer, assuming it is all there
 * This is indended for use with ethernet
 * This function will not test the CRC
 * @param buf - the buffer for this packet, also the state of the receive routine
 * @return BB_GOOD if a valid packet was received, BB_FAIL if the packet was bad
 */
BbResult blueberryReceiveAndParsePacket(Bb* bb){
	BbResult result = blueberryReceivePacket(bb);
	if(result == BB_GOOD){
		parseBbPacket(bb);
	}
	return result;
}
/**
 * scans the next byte the input queue for packets, if found will respond with a response packet on the output queue.
 * this funcion will only process at most n bytes at a time
 * It uses the input buffer to store the recieving state between calls.
 * @param bb - the buffer for this packet, also the state of the receive routine
 * @return BB_GOOD if a valid packet was received, BB_FAIL if the packet was bad, BB_INCOMPLETE if it's good so far but more bytes are needed
 */
BbResult blueberryReceiveAndParseByte(Bb* bb){
	BbResult result = blueberryReceiveByte(bb);
	if(result == BB_GOOD){
		parseBbPacket(bb);
	}

	return result;
}


