/*
Copyright (c) 2025 Blue Robotics North Inc.

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/


//*******************************************************************************************
//Includes
//*******************************************************************************************
#include <blueberry-receiver.h>
#include <blueberry-transcoder.h>
#include <blueberry-parser.h>


//*******************************************************************************************
//Defines
//*******************************************************************************************



//*******************************************************************************************
//Types
//*******************************************************************************************

//*******************************************************************************************
//Variables
//*******************************************************************************************



//*******************************************************************************************
//Function Prototypes
//*******************************************************************************************


/**
 * Receive one bytes from the queue.
 * If the queue has less than n bytes available, then only use what is available.
 * This is intended for use with a UART
 * This functi0n will test the CRC
 * @param s - state for this routine to allow for multiple calls
 * @param q - the queue that the new bytes are coming from
 * @param n - the maximum number of bytes to process - this is to limit the type that this routine will take at one calling
 *
 */
static BbResult blueberryReceiveByte(Bb* bb);

/**
 * Decodes a packet from the start of a buffer, assuming it is all there
 * This is indended for use with ethernet
 * This function will not test the CRC
 * This function will discard the queue contents if the packet fails the checks
 * This is implemented with function pointers. I tried to avoid them but it allows easy inclusion into the autogenerated code
 * @param buf - the buffer for this packet, also the state of the receive routine
 * @return true if a valid packet was received
 */
static BbResult blueberryReceivePacket(Bb* buf);
//*******************************************************************************************
//Code
//*******************************************************************************************

/**
 * Receive one bytes from the queue.
 * If the queue has less than n bytes available, then only use what is available.
 * This is intended for use with a UART
 * This function will test the CRC
 * This function will discard bytes from the queue if they are bad
 * This is implemented with function pointers. I tried to avoid them but it allows easy inclusion into the autogenerated code
 * the length field of the Bb packet field is used as a state variable. Zero indicates the state is reset. After that it indicates how many bytes have been successfully received
 * @param buf - the buffer for this packet, also the state of the receive routine
 * @param q - the queue that the new bytes are coming from
 * @param n - the maximum number of bytes to process - this is to limit the type that this routine will take at one calling
 * @return true if a valid packet was received
 *
 */
static BbResult blueberryReceiveByte(Bb* buf){
	BbResult result = BB_INCOMPLETE;

	++(buf->length);

	if(!minBbLengthCheck(buf)){
		if(!checkBbPreamble(buf)){
			result = BB_FAIL;
		}
	} else if(checkBbLength(buf)){
		if(checkBbCrc(buf)){
			result = BB_GOOD;//we have a valid packet
			//any remaining bytes should be checked after this packet has been consumed
		} else {
			result = BB_FAIL;
		}
	}



	return result;
}

/**
 * Decodes a packet from the start of a buffer, assuming it is all there
 * This is indended for use with ethernet
 * This function will not test the CRC
 * This function will discard the queue contents if the packet fails the checks
 * This is implemented with function pointers. I tried to avoid them but it allows easy inclusion into the autogenerated code
 * @param buf - the buffer for this packet, also the state of the receive routine
 * @return true if a valid packet was received
 */
static BbResult blueberryReceivePacket(Bb* buf){
	BbResult result = BB_FAIL;

	if(minBbLengthCheck(buf)){
		if(checkBbPreamble(buf)){
			if(checkBbLength(buf)){
				result = BB_GOOD;
			}
		}
	}



	return result;


}


/**
 * Decodes a packet from the start of a buffer, assuming it is all there
 * This is indended for use with ethernet
 * This function will not test the CRC
 * @param buf - the buffer for this packet, also the state of the receive routine
 * @return BB_GOOD if valid packet else BB_FAIL
 */
BbResult blueberryReceiveAndParsePacket(Bb* bb){
	BbResult result = blueberryReceivePacket(bb);
	if(result == BB_GOOD){
		parseBbPacket(bb);

	}
	return result;
}

BbResult blueberryReceiveAndParseByte(Bb* bb){
	BbResult result = blueberryReceiveByte(bb);
	if(result == BB_GOOD){
		parseBbPacket(bb);
	}

	return result;
}




///**
// * Checks if we've recevied a packet within the specified time. Specifically checks to see if we HAVEN'T
// * @param microseconds - the specified timeout
// * @return true if time since last received packet is greater than the specified time
// */
//bool isLastPacketTimeNotWithin(uint32_t microseconds){
//	return slowTimer(&m_lastRxTime, microseconds);
//}

